FROM python:3.11.1 as requirements-stage

WORKDIR /tmp

RUN pip install poetry

COPY ./pyproject.toml ./poetry.lock* /tmp/

RUN poetry export -f requirements.txt --output requirements.txt --without-hashes

FROM python:3.11.1

WORKDIR /RESTAURANT-CRM

COPY --from=requirements-stage /tmp/requirements.txt /RESTAURANT-CRM/requirements.txt

RUN apt-get update \
    && apt-get install gcc -y \
    && apt-get install libpq-dev -y \
    && apt-get clean

RUN pip install --no-cache-dir --upgrade -r /RESTAURANT-CRM/requirements.txt

COPY . /RESTAURANT-CRM/

RUN chmod u+x ./entrypoint.sh
ENTRYPOINT ["./entrypoint.sh"]
