FROM python:3.10 as requirements-stage

WORKDIR /tmp

RUN pip install poetry

COPY ./pyproject.toml ./poetry.lock* /tmp/

RUN poetry export -f requirements.txt --output requirements.txt --without-hashes

FROM python:3.10

WORKDIR /e_commerce

COPY --from=requirements-stage /tmp/requirements.txt /e_commerce/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /e_commerce/requirements.txt

COPY ./e_commerce /e_commerce/e_commerce

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8081"]