version: '3.9'
services:
  db:
    image: postgres:14.6-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5445:5432
    env_file:
      - ./restaurant_crm/db.env
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U mhbp -d restaurant_crm'"]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: always

  backend:
    build: .
    volumes:
      - ./restaurant_crm/:/restaurant_crm/
    entrypoint: ./entrypoint.sh
    env_file:
      - ./restaurant_crm/.env
    ports:
      - 8007:8000
    depends_on:
      db:
        condition: service_healthy
    restart: always
  
volumes:
    postgres_data: